version: '2'
services:
  db:
    image: postgres:9.6
    volumes: 
       - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=iris-db
      - POSTGRES_USER=iris-user
      - POSTGRES_PASSWORD=iris-password
    ports:
      - "5432:5432"

